// public/frontend/src/routes/aliases.svelte
<script lang="ts">
	import AliasList from '$lib/AliasList.svelte';

	let dummyData = [
		{Name:"Facebook", Address: "john.doe@chameleon.io", WhitelistPattern: ".*@facebook\\.com", LastUsed: 5, EncryptionEnabled: true},
		{Name:"Google", Address: "jupiter_push@chameleon.io", WhitelistPattern: ".*@google\\.com", LastUsed: 3, EncryptionEnabled: true},
		{Name:"Somewhere Dodgy", Address: "andromeda-audio@chameleon.io", WhitelistPattern: ".*@somewhere-dodgy\\.com", LastUsed: 2, EncryptionEnabled: false}
	]
</script>
<svelte:head>
	<title>Aliases</title>
</svelte:head>

<div>
	<h1 class='text-2xl'>Aliases</h1>
	<AliasList aliases={dummyData} />
</div>

// public/frontend/src/components/pages/aliases.tsx
import React from 'react';
import useDocTitle from '../hooks/useDocTitle';
import Alias from '../../model/alias';
import AliasList from '../alias/aliasList';

const Aliases = () => {

    const [docTitle, setDocTitle] = useDocTitle("Aliases");

	let dummyData: Alias[] = [
		{Name:"Facebook", Address: "john.doe@chameleon.io", WhitelistPattern: ".*@facebook\\.com", LastUsed: 5, EncryptionEnabled: true, IsActive: true},
		{Name:"Google", Address: "jupiter_push@chameleon.io", WhitelistPattern: ".*@google\\.com", LastUsed: 3, EncryptionEnabled: true, IsActive: true},
		{Name:"Somewhere Dodgy", Address: "andromeda-audio@chameleon.io", WhitelistPattern: ".*@somewhere-dodgy\\.com", LastUsed: 2, EncryptionEnabled: false, IsActive: false}
	]

    return (
        <div>
            <h1 className="text-2xl">Aliases</h1>
            <AliasList Aliases={dummyData} AllowAdd={true}/>
        </div>
    );
}

export default Aliases;
