// public/frontend/src/lib/components/Section.svelte
<script lang='ts'>
	import { TextSize, textSizeToClassName } from '$lib/model/TextSize';

	export let header: string;
	export let headerSize: TextSize = TextSize.ExtraLarge;
	export let className: string | undefined;
</script>

<div class='flex flex-col gap-1 {className}'>
	<h1 class='{textSizeToClassName(headerSize)} border-b border-gray-300'>{header}</h1>
	<div class='p-1'>
		<slot />
	</div>
</div>

// public/frontend/src/components/section.tsx
import React, { PropsWithChildren } from 'react';
import { TextSize, textSizeToClassName } from '../model/TextSize';
import PropsWithClassName from './PropsWithClassName';

type SectionProps = PropsWithChildren<{
    header: string;
    headerSize?: TextSize;
 }> & PropsWithClassName;

const Section = (props: SectionProps) => {

    let headerSize = props.headerSize ?? TextSize.ExtraLarge;

    return (
        <div className={`flex flex-col gap-1 pt-2 ${props.className}`}>
            <h1 className={`${textSizeToClassName(headerSize)} border-b border-gray-300`}>
                {props.header}
            </h1>
            <div className='p-1'>
                {props.children}
            </div>
        </div>
    );
};

export default Section;
