// public/frontend/src/lib/components/header/Navbar.svelte
<script>
	import UserCircle from '$lib/components/icons/UserCircle.svelte';
	import NotificationIcon from '$lib/components/icons/NotificationIcon.svelte';
	import Link from '$lib/components/header/Link.svelte';
	import Dropdown from '$lib/components/Dropdown.svelte';
	import DropdownItem from '$lib/components/DropdownItem.svelte';
</script>

<div class="items-center justify-between flex bg-green-500 text-white bg-opacity-90 px-24 py-2 shadow-2xl">

	<!-- Left -->
	<div class="inline-flex items-center">

		<!-- Todo: Logo -->
		<div class="text-2xl text-white font-semibold inline-flex">
			<span>Chameleon</span>
		</div>

		<!-- Links -->
		<div class='ml-5 flex'>
			<Link className='mx-2' path='/aliases'>Aliases</Link>
			<Link className='mx-1' path='/quarantined'>Quarantined</Link>
		</div>
	</div>

	<!-- Right -->
	<!-- Todo: These should be dropdowns -->
	<div class="inline-flex items-center">
		<Link className='mx-1' path='/notifications'><NotificationIcon /></Link>

		<Dropdown>
			<span slot='button'>
				<Link className='mx-1'><UserCircle /></Link>
			</span>
			<span slot='items'>
				<DropdownItem>
					<a href='/account'>My Account</a>
				</DropdownItem>
				<DropdownItem>
					<a href='/settings'>Settings</a>
				</DropdownItem>
				<DropdownItem>
					<a href='/logout'>Log Out</a>
				</DropdownItem>
			</span>
		</Dropdown>
	</div>
</div>

// public/frontend/src/components/header/Navbar.tsx
import React from 'react';
import Link from './Link';
import NotificationIcon from '../icons/NotificationIcon';
import Dropdown from '../Dropdown';
import DropdownItem from '../DropdownItem';
import UserCircle from '../icons/UserCircle';
import '../DropdownItem.css';

const Navbar = () => {
    return (
        <div className="items-center justify-between flex bg-green-500 text-white bg-opacity-90 px-24 py-2 shadow-2xl">

            {/* Left */}
            <div className="inline-flex items-center">

                {/* Todo: Logo */}
                <div className="text-2xl text-white font-semibold inline-flex">
                    <span>Chameleon</span>
                </div>

                {/* Links */}
                <div className='ml-5 flex'>
                    <Link className='mx-2' path='/aliases'>Aliases</Link>
                    <Link className='mx-1' path='/quarantined'>Quarantined</Link>
                </div>
            </div>

            {/* Right */}
            {/* Todo: These should be dropdowns */}
            <div className="inline-flex items-center">
                <Link className='mx-1' path='/notifications'><NotificationIcon HasUnreadNotifications={false} className="h-6 w-6"/></Link>

                {/* Todo: The active state of these links looks weird */}
                <Dropdown button={<Link className='mx-1'><UserCircle className="h-6 w-6"/></Link>}>
                    <DropdownItem>
                        <Link path='/account'>My Account</Link>
                    </DropdownItem>
                    <DropdownItem>
                        <Link path='/settings'>Settings</Link>
                    </DropdownItem>
                    <DropdownItem>
                        <Link path='/logout'>Log Out</Link>
                    </DropdownItem>
                </Dropdown>
            </div>
        </div>
    );
}

export default Navbar;
