// public/frontend/src/components/alias/aliasList.tsx
import React from 'react';
import Alias from '../../model/alias';
import AliasListItem from './aliasListItem';

interface AliasListProps {
    Aliases: Alias[];
    AllowAdd: boolean;
}

const AliasList = (props: AliasListProps) => {
    return (
        <div className='flex flex-row grid grid-cols-2 gap-4'>
            {props.Aliases.map(alias => {
                return <AliasListItem key={alias.Address} Alias={alias} />
            })}

            {props.AllowAdd && <AliasListItem IsTemplate={true} />}
        </div>
    );
}

export default AliasList;

// public/frontend/src/lib/components/AliasList.svelte

<script lang="ts">
	import AliasListItem from '$lib/components/AliasListItem.svelte';
	import type Alias from '$lib/model/alias';

	export let aliases: Alias[] = [];
	export let allowAdd = true;
</script>

<div class='flex flex-row grid grid-cols-2 gap-4'>
	{#each aliases as alias}
		<AliasListItem alias={alias} />
	{/each}

	{#if allowAdd}
		<AliasListItem isTemplate={true} />
	{/if}
</div>
