// public/frontend/src/components/Dropdown.tsx
import React, { useState, useRef, useCallback, PropsWithChildren } from 'react';
import useOnClickOutside from './hooks/useClickOutside';

type DropdownProps = PropsWithChildren<{
    button: React.ReactNode;
}>;

const Dropdown = (props: DropdownProps) => {

    const [isOpen, setIsOpen] = useState(false);

    const dropdownRef = useRef<HTMLDivElement>(null);

    const hideDropdown = useCallback(() => setIsOpen(false), []);
    const toggleDropdown = useCallback(() => setIsOpen(!isOpen), [isOpen]);

    useOnClickOutside(dropdownRef, (_: any) => hideDropdown());

    return (
        <div className="relative" ref={dropdownRef}>
            <div onClick={toggleDropdown}>
                {props.button}
            </div>
            {isOpen && (
                <div className='absolute right-0 mt-2 py-2 w-40 bg-white rounded-md shadow-md' onClick={hideDropdown}>
                    {props.children}
                </div>
            )}
        </div>
    );
}

export default Dropdown;

// public/frontend/src/lib/components/Dropdown.svelte
<script lang="ts">
	export let isOpen = false;
	const toggleDropdown = () => isOpen = !isOpen;

	const hideDropdown = () => {
		isOpen = false;
	}

	let dropdownElement;
	function isInDropdown(target) {
		let parent = target;
		while (parent) {
			if (parent === dropdownElement)
				return true;

			parent = parent.parentNode;
		}

		return false;
	}

	const onClickOutside = (event) => {
		if (isInDropdown(event.target))
			return;

		hideDropdown();
	}
</script>

<svelte:body on:click={onClickOutside} />

<div class="relative" bind:this={dropdownElement}>
	<div on:click={toggleDropdown}>
		<slot name='button' />
	</div>
	{#if isOpen}
		<div class='absolute right-0 mt-2 py-2 w-40 bg-white rounded-md shadow-md' on:click={hideDropdown}>
			<slot name='items' />
		</div>
	{/if}
</div>
